# Generated by Django 3.2 on 2021-05-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210508_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_created',
        ),
    ]
